TRUNCATE TABLE gallery;
INSERT INTO gallery (image_url, caption, category) VALUES ('images/ballon/₹2 SNAKE BALLOON.jpg', '₹2 SNAKE BALLOON', 'ballon');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1000', '₹2 SNAKE BALLOON', 'Balloons & Birthday Decor', 'Sri Amman Toys', 'ballon', 2, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/ballon/₹5 JUMPOO BALLOON.jpg', '₹5 JUMPOO BALLOON', 'ballon');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1001', '₹5 JUMPOO BALLOON', 'Balloons & Birthday Decor', 'Sri Amman Toys', 'ballon', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/Boomer.jpg', 'Boomer', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1002', 'Boomer', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/Eye balls.jpg', 'Eye balls', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1003', 'Eye balls', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/IMG-20260708-WA0073.jpg', 'Sri Amman Item', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1004', 'Sri Amman Item', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹0.50 paisa Coin Sudam Pkt.jpg', '₹0.50 paisa Coin Sudam Pkt', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1005', '₹0.50 paisa Coin Sudam Pkt', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 0.5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹0.50 Paisa Crazy'' Jamm.jpg', '₹0.50 Paisa Crazy'' Jamm', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1006', '₹0.50 Paisa Crazy'' Jamm', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 0.5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹1 Anbu Palkova.jpg', '₹1 Anbu Palkova', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1007', '₹1 Anbu Palkova', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 1, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹1 Bottle Candy.jpg', '₹1 Bottle Candy', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1008', '₹1 Bottle Candy', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 1, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹1 Cube Seeni Jelly Pkt.jpg', '₹1 Cube Seeni Jelly Pkt', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1009', '₹1 Cube Seeni Jelly Pkt', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 1, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹1 Koffee Jar.jpg', '₹1 Koffee Jar', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1010', '₹1 Koffee Jar', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 1, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹1 Kofilik.jpg', '₹1 Kofilik', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1011', '₹1 Kofilik', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 1, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹1 Kopiko Original.jpg', '₹1 Kopiko Original', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1012', '₹1 Kopiko Original', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 1, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹1 Orange jar.jpg', '₹1 Orange jar', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1013', '₹1 Orange jar', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 1, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹1 pakku jar.jpg', '₹1 pakku jar', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1014', '₹1 pakku jar', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 1, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹1 panda.jpg', '₹1 panda', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1015', '₹1 panda', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 1, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹1 Paththi Kutchi Jug.jpg', '₹1 Paththi Kutchi Jug', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1016', '₹1 Paththi Kutchi Jug', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 1, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹1 Pulikrandi Jar.jpg', '₹1 Pulikrandi Jar', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1017', '₹1 Pulikrandi Jar', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 1, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹1 Sudam jar.jpg', '₹1 Sudam jar', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1018', '₹1 Sudam jar', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 1, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹1 Wheel Mittai Jar.jpg', '₹1 Wheel Mittai Jar', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1019', '₹1 Wheel Mittai Jar', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 1, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹1 Winner Kamarkattu Pkt.jpg', '₹1 Winner Kamarkattu Pkt', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1020', '₹1 Winner Kamarkattu Pkt', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 1, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹1 Wonder Ball.jpg', '₹1 Wonder Ball', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1021', '₹1 Wonder Ball', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 1, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹2 CC Stick.jpg', '₹2 CC Stick', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1022', '₹2 CC Stick', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 2, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹2 Drinking Jelly.jpg', '₹2 Drinking Jelly', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1023', '₹2 Drinking Jelly', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 2, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹2 Fassion Cone.jpg', '₹2 Fassion Cone', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1024', '₹2 Fassion Cone', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 2, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹2 Fru Pop Lolipop.jpg', '₹2 Fru Pop Lolipop', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1025', '₹2 Fru Pop Lolipop', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 2, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹2 Masti Lolipop.jpg', '₹2 Masti Lolipop', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1026', '₹2 Masti Lolipop', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 2, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹2 popo jelly.jpg', '₹2 popo jelly', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1027', '₹2 popo jelly', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 2, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹5 Aura Chocolate Box.jpg', '₹5 Aura Chocolate Box', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1028', '₹5 Aura Chocolate Box', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹5 Berry Berry.jpg', '₹5 Berry Berry', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1029', '₹5 Berry Berry', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹5 Berry Blast.jpg', '₹5 Berry Blast', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1030', '₹5 Berry Blast', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹5 Butterfly Jelly.jpg', '₹5 Butterfly Jelly', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1031', '₹5 Butterfly Jelly', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹5 Chocolate Cone.jpg', '₹5 Chocolate Cone', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1032', '₹5 Chocolate Cone', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹5 Cookie Lolipop.jpg', '₹5 Cookie Lolipop', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1033', '₹5 Cookie Lolipop', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹5 Crispy Puff.jpg', '₹5 Crispy Puff', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1034', '₹5 Crispy Puff', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹5 Cycle Light with Candy.jpg', '₹5 Cycle Light with Candy', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1035', '₹5 Cycle Light with Candy', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹5 Dazzy Big Star ⭐.jpg', '₹5 Dazzy Big Star ⭐', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1036', '₹5 Dazzy Big Star ⭐', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹5 Devi Fan Lolipop.jpg', '₹5 Devi Fan Lolipop', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1037', '₹5 Devi Fan Lolipop', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹5 Devi Toys Free Lolipop.jpg', '₹5 Devi Toys Free Lolipop', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1038', '₹5 Devi Toys Free Lolipop', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹5 Double Side King Egg  Box.jpg', '₹5 Double Side King Egg  Box', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1039', '₹5 Double Side King Egg  Box', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹5 Elandha cup.jpg', '₹5 Elandha cup', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1040', '₹5 Elandha cup', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹5 Fire Spray.jpg', '₹5 Fire Spray', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1041', '₹5 Fire Spray', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹5 Livinda Fresh Mint.jpg', '₹5 Livinda Fresh Mint', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1042', '₹5 Livinda Fresh Mint', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹5 Mango Cake Jelly Box.jpg', '₹5 Mango Cake Jelly Box', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1043', '₹5 Mango Cake Jelly Box', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹5 Milky Blast.jpg', '₹5 Milky Blast', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1044', '₹5 Milky Blast', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹5 Push Up Cone.jpg', '₹5 Push Up Cone', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1045', '₹5 Push Up Cone', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹5 Rich Choco Gems.jpg', '₹5 Rich Choco Gems', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1046', '₹5 Rich Choco Gems', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹5 Strawberry Cake Jelly Box.jpg', '₹5 Strawberry Cake Jelly Box', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1047', '₹5 Strawberry Cake Jelly Box', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹5 sweet morning.jpg', '₹5 sweet morning', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1048', '₹5 sweet morning', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/Chocolate/₹5 Watermelon Pop 🍉.jpg', '₹5 Watermelon Pop 🍉', 'Chocolate');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1049', '₹5 Watermelon Pop 🍉', 'Chocolates', 'Sri Amman Toys', 'Chocolate', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/chocolate2/jelly sweets.jpg', 'jelly sweets', 'chocolate2');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1050', 'jelly sweets', 'Wafers & Party Treats', 'Sri Amman Toys', 'chocolate2', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/chocolate2/₹0.50Paisa Saravana Pallies Ja.jpg', '₹0.50Paisa Saravana Pallies Ja', 'chocolate2');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1051', '₹0.50Paisa Saravana Pallies Ja', 'Wafers & Party Treats', 'Sri Amman Toys', 'chocolate2', 0.5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/chocolate2/₹1 Bubblegum Atta.jpg', '₹1 Bubblegum Atta', 'chocolate2');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1052', '₹1 Bubblegum Atta', 'Wafers & Party Treats', 'Sri Amman Toys', 'chocolate2', 1, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/chocolate2/₹1 Choco Roll.jpg', '₹1 Choco Roll', 'chocolate2');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1053', '₹1 Choco Roll', 'Wafers & Party Treats', 'Sri Amman Toys', 'chocolate2', 1, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/chocolate2/₹1 Strawberry Roll.jpg', '₹1 Strawberry Roll', 'chocolate2');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1054', '₹1 Strawberry Roll', 'Wafers & Party Treats', 'Sri Amman Toys', 'chocolate2', 1, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/chocolate2/₹1 Tattoos Boomer.jpg', '₹1 Tattoos Boomer', 'chocolate2');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1055', '₹1 Tattoos Boomer', 'Wafers & Party Treats', 'Sri Amman Toys', 'chocolate2', 1, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/chocolate2/₹5 Biscuit Box.jpg', '₹5 Biscuit Box', 'chocolate2');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1056', '₹5 Biscuit Box', 'Wafers & Party Treats', 'Sri Amman Toys', 'chocolate2', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/chocolate2/₹5 FINGERS lolipop.jpg', '₹5 FINGERS lolipop', 'chocolate2');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1057', '₹5 FINGERS lolipop', 'Wafers & Party Treats', 'Sri Amman Toys', 'chocolate2', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/chocolate2/₹5 Gold Khazana.jpg', '₹5 Gold Khazana', 'chocolate2');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1058', '₹5 Gold Khazana', 'Wafers & Party Treats', 'Sri Amman Toys', 'chocolate2', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/chocolate2/₹5 Kinder Joy Cream.jpg', '₹5 Kinder Joy Cream', 'chocolate2');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1059', '₹5 Kinder Joy Cream', 'Wafers & Party Treats', 'Sri Amman Toys', 'chocolate2', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/chocolate2/₹5 Teddy Bear Lolipop.jpg', '₹5 Teddy Bear Lolipop', 'chocolate2');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1060', '₹5 Teddy Bear Lolipop', 'Wafers & Party Treats', 'Sri Amman Toys', 'chocolate2', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/chocolate2/₹5 vala gems.jpg', '₹5 vala gems', 'chocolate2');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1061', '₹5 vala gems', 'Wafers & Party Treats', 'Sri Amman Toys', 'chocolate2', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/prices/IMG-20260708-WA0198.jpg', 'Sri Amman Item', 'prices');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1062', 'Sri Amman Item', 'Price Stickers & Tags', 'Sri Amman Toys', 'prices', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/prices/IMG-20260708-WA0199.jpg', 'Sri Amman Item', 'prices');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1063', 'Sri Amman Item', 'Price Stickers & Tags', 'Sri Amman Toys', 'prices', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/prices/IMG-20260708-WA0200.jpg', 'Sri Amman Item', 'prices');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1064', 'Sri Amman Item', 'Price Stickers & Tags', 'Sri Amman Toys', 'prices', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/prices/IMG-20260708-WA0201.jpg', 'Sri Amman Item', 'prices');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1065', 'Sri Amman Item', 'Price Stickers & Tags', 'Sri Amman Toys', 'prices', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/prices/IMG-20260708-WA0202.jpg', 'Sri Amman Item', 'prices');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1066', 'Sri Amman Item', 'Price Stickers & Tags', 'Sri Amman Toys', 'prices', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/prices/IMG-20260708-WA0203.jpg', 'Sri Amman Item', 'prices');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1067', 'Sri Amman Item', 'Price Stickers & Tags', 'Sri Amman Toys', 'prices', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/prices/IMG-20260708-WA0206.jpg', 'Sri Amman Item', 'prices');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1068', 'Sri Amman Item', 'Price Stickers & Tags', 'Sri Amman Toys', 'prices', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/prices/IMG-20260708-WA0207.jpg', 'Sri Amman Item', 'prices');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1069', 'Sri Amman Item', 'Price Stickers & Tags', 'Sri Amman Toys', 'prices', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/stickersz and cards/5 pieces cutout stickerz gods.jpg', '5 pieces cutout stickerz gods', 'stickersz and cards');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1070', '5 pieces cutout stickerz gods', 'Greeting Cards & Stickers', 'Sri Amman Toys', 'stickersz and cards', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/stickersz and cards/IMG-20260708-WA0142.jpg', 'Sri Amman Item', 'stickersz and cards');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1071', 'Sri Amman Item', 'Greeting Cards & Stickers', 'Sri Amman Toys', 'stickersz and cards', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/stickersz and cards/IMG-20260708-WA0143.jpg', 'Sri Amman Item', 'stickersz and cards');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1072', 'Sri Amman Item', 'Greeting Cards & Stickers', 'Sri Amman Toys', 'stickersz and cards', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/stickersz and cards/IMG-20260708-WA0145.jpg', 'Sri Amman Item', 'stickersz and cards');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1073', 'Sri Amman Item', 'Greeting Cards & Stickers', 'Sri Amman Toys', 'stickersz and cards', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/stickersz and cards/IMG-20260708-WA0146.jpg', 'Sri Amman Item', 'stickersz and cards');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1074', 'Sri Amman Item', 'Greeting Cards & Stickers', 'Sri Amman Toys', 'stickersz and cards', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/stickersz and cards/IMG-20260708-WA0147.jpg', 'Sri Amman Item', 'stickersz and cards');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1075', 'Sri Amman Item', 'Greeting Cards & Stickers', 'Sri Amman Toys', 'stickersz and cards', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/stickersz and cards/IMG-20260708-WA0148.jpg', 'Sri Amman Item', 'stickersz and cards');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1076', 'Sri Amman Item', 'Greeting Cards & Stickers', 'Sri Amman Toys', 'stickersz and cards', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/stickersz and cards/IMG-20260708-WA0149.jpg', 'Sri Amman Item', 'stickersz and cards');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1077', 'Sri Amman Item', 'Greeting Cards & Stickers', 'Sri Amman Toys', 'stickersz and cards', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/stickersz and cards/IMG-20260708-WA0151.jpg', 'Sri Amman Item', 'stickersz and cards');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1078', 'Sri Amman Item', 'Greeting Cards & Stickers', 'Sri Amman Toys', 'stickersz and cards', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/stickersz and cards/IMG-20260708-WA0153.jpg', 'Sri Amman Item', 'stickersz and cards');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1079', 'Sri Amman Item', 'Greeting Cards & Stickers', 'Sri Amman Toys', 'stickersz and cards', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/stickersz and cards/IMG-20260708-WA0154.jpg', 'Sri Amman Item', 'stickersz and cards');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1080', 'Sri Amman Item', 'Greeting Cards & Stickers', 'Sri Amman Toys', 'stickersz and cards', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/stickersz and cards/IMG-20260708-WA0155.jpg', 'Sri Amman Item', 'stickersz and cards');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1081', 'Sri Amman Item', 'Greeting Cards & Stickers', 'Sri Amman Toys', 'stickersz and cards', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/stickersz and cards/IMG-20260708-WA0156.jpg', 'Sri Amman Item', 'stickersz and cards');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1082', 'Sri Amman Item', 'Greeting Cards & Stickers', 'Sri Amman Toys', 'stickersz and cards', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/stickersz and cards/IMG-20260708-WA0157.jpg', 'Sri Amman Item', 'stickersz and cards');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1083', 'Sri Amman Item', 'Greeting Cards & Stickers', 'Sri Amman Toys', 'stickersz and cards', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/stickersz and cards/IMG-20260708-WA0158.jpg', 'Sri Amman Item', 'stickersz and cards');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1084', 'Sri Amman Item', 'Greeting Cards & Stickers', 'Sri Amman Toys', 'stickersz and cards', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/stickersz and cards/IMG-20260708-WA0159.jpg', 'Sri Amman Item', 'stickersz and cards');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1085', 'Sri Amman Item', 'Greeting Cards & Stickers', 'Sri Amman Toys', 'stickersz and cards', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/stickersz and cards/IMG-20260708-WA0160.jpg', 'Sri Amman Item', 'stickersz and cards');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1086', 'Sri Amman Item', 'Greeting Cards & Stickers', 'Sri Amman Toys', 'stickersz and cards', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/stickersz and cards/IMG-20260708-WA0161.jpg', 'Sri Amman Item', 'stickersz and cards');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1087', 'Sri Amman Item', 'Greeting Cards & Stickers', 'Sri Amman Toys', 'stickersz and cards', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/stickersz and cards/IMG-20260708-WA0162.jpg', 'Sri Amman Item', 'stickersz and cards');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1088', 'Sri Amman Item', 'Greeting Cards & Stickers', 'Sri Amman Toys', 'stickersz and cards', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/stickersz and cards/IMG-20260708-WA0173.jpg', 'Sri Amman Item', 'stickersz and cards');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1089', 'Sri Amman Item', 'Greeting Cards & Stickers', 'Sri Amman Toys', 'stickersz and cards', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/stickersz and cards/tattoo.jpg', 'tattoo', 'stickersz and cards');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1090', 'tattoo', 'Greeting Cards & Stickers', 'Sri Amman Toys', 'stickersz and cards', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/stickersz and cards/vijay stickerz.jpg', 'vijay stickerz', 'stickersz and cards');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1091', 'vijay stickerz', 'Greeting Cards & Stickers', 'Sri Amman Toys', 'stickersz and cards', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/stickersz and cards/₹5 Bheem Sticker.jpg', '₹5 Bheem Sticker', 'stickersz and cards');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1092', '₹5 Bheem Sticker', 'Greeting Cards & Stickers', 'Sri Amman Toys', 'stickersz and cards', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/stickersz and cards/₹5 Naruto 5pcs Stickers.jpg', '₹5 Naruto 5pcs Stickers', 'stickersz and cards');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1093', '₹5 Naruto 5pcs Stickers', 'Greeting Cards & Stickers', 'Sri Amman Toys', 'stickersz and cards', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/stickersz and cards/₹5 New Model Tattoos.jpg', '₹5 New Model Tattoos', 'stickersz and cards');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1094', '₹5 New Model Tattoos', 'Greeting Cards & Stickers', 'Sri Amman Toys', 'stickersz and cards', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/toys/10rs pencil set.jpg', '10rs pencil set', 'toys');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1095', '10rs pencil set', 'Toys & Educational Games', 'Sri Amman Toys', 'toys', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/toys/IMG-20260708-WA0152.jpg', 'Sri Amman Item', 'toys');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1096', 'Sri Amman Item', 'Toys & Educational Games', 'Sri Amman Toys', 'toys', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/toys/IMG-20260708-WA0165.jpg', 'Sri Amman Item', 'toys');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1097', 'Sri Amman Item', 'Toys & Educational Games', 'Sri Amman Toys', 'toys', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/toys/IMG-20260708-WA0166.jpg', 'Sri Amman Item', 'toys');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1098', 'Sri Amman Item', 'Toys & Educational Games', 'Sri Amman Toys', 'toys', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/toys/IMG-20260708-WA0167.jpg', 'Sri Amman Item', 'toys');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1099', 'Sri Amman Item', 'Toys & Educational Games', 'Sri Amman Toys', 'toys', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/toys/IMG-20260708-WA0168.jpg', 'Sri Amman Item', 'toys');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1100', 'Sri Amman Item', 'Toys & Educational Games', 'Sri Amman Toys', 'toys', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/toys/IMG-20260708-WA0169.jpg', 'Sri Amman Item', 'toys');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1101', 'Sri Amman Item', 'Toys & Educational Games', 'Sri Amman Toys', 'toys', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/toys/IMG-20260708-WA0170.jpg', 'Sri Amman Item', 'toys');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1102', 'Sri Amman Item', 'Toys & Educational Games', 'Sri Amman Toys', 'toys', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/toys/IMG-20260708-WA0171.jpg', 'Sri Amman Item', 'toys');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1103', 'Sri Amman Item', 'Toys & Educational Games', 'Sri Amman Toys', 'toys', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/toys/IMG-20260708-WA0212.jpg', 'Sri Amman Item', 'toys');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1104', 'Sri Amman Item', 'Toys & Educational Games', 'Sri Amman Toys', 'toys', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/toys/kidsz toys.jpg', 'kidsz toys', 'toys');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1105', 'kidsz toys', 'Toys & Educational Games', 'Sri Amman Toys', 'toys', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/toys/Metal Body Push Back Airplane ✈️.jpg', 'Metal Body Push Back Airplane ✈️', 'toys');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1106', 'Metal Body Push Back Airplane ✈️', 'Toys & Educational Games', 'Sri Amman Toys', 'toys', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/toys/Metal Body Push Back Jeep.jpg', 'Metal Body Push Back Jeep', 'toys');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1107', 'Metal Body Push Back Jeep', 'Toys & Educational Games', 'Sri Amman Toys', 'toys', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/toys/Metal Body Push Back Race Car.jpg', 'Metal Body Push Back Race Car', 'toys');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1108', 'Metal Body Push Back Race Car', 'Toys & Educational Games', 'Sri Amman Toys', 'toys', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/toys/parachute.jpg', 'parachute', 'toys');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1109', 'parachute', 'Toys & Educational Games', 'Sri Amman Toys', 'toys', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/toys/spinning top.jpg', 'spinning top', 'toys');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1110', 'spinning top', 'Toys & Educational Games', 'Sri Amman Toys', 'toys', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/toys/vijay chain.jpg', 'vijay chain', 'toys');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1111', 'vijay chain', 'Toys & Educational Games', 'Sri Amman Toys', 'toys', 0, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/toys/₹10 Bubbles Jar.jpg', '₹10 Bubbles Jar', 'toys');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1112', '₹10 Bubbles Jar', 'Toys & Educational Games', 'Sri Amman Toys', 'toys', 10, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/toys/₹15 Push Back Mix.jpg', '₹15 Push Back Mix', 'toys');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1113', '₹15 Push Back Mix', 'Toys & Educational Games', 'Sri Amman Toys', 'toys', 15, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/toys/₹5 Baby Purse Khazana.jpg', '₹5 Baby Purse Khazana', 'toys');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1114', '₹5 Baby Purse Khazana', 'Toys & Educational Games', 'Sri Amman Toys', 'toys', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/toys/₹5 Bubbles Jar.jpg', '₹5 Bubbles Jar', 'toys');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1115', '₹5 Bubbles Jar', 'Toys & Educational Games', 'Sri Amman Toys', 'toys', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/toys/₹5 Cycle Gift Box.jpg', '₹5 Cycle Gift Box', 'toys');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1116', '₹5 Cycle Gift Box', 'Toys & Educational Games', 'Sri Amman Toys', 'toys', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/toys/₹5 Dori Jumping Boll.jpg', '₹5 Dori Jumping Boll', 'toys');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1117', '₹5 Dori Jumping Boll', 'Toys & Educational Games', 'Sri Amman Toys', 'toys', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/toys/₹5 Glass 😎.jpg', '₹5 Glass 😎', 'toys');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1118', '₹5 Glass 😎', 'Toys & Educational Games', 'Sri Amman Toys', 'toys', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/toys/₹5 Glay.jpg', '₹5 Glay', 'toys');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1119', '₹5 Glay', 'Toys & Educational Games', 'Sri Amman Toys', 'toys', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/toys/₹5 Heart Atta.jpg', '₹5 Heart Atta', 'toys');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1120', '₹5 Heart Atta', 'Toys & Educational Games', 'Sri Amman Toys', 'toys', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/toys/₹5 Hero Ball.jpg', '₹5 Hero Ball', 'toys');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1121', '₹5 Hero Ball', 'Toys & Educational Games', 'Sri Amman Toys', 'toys', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/toys/₹5 House Gift Box.jpg', '₹5 House Gift Box', 'toys');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1122', '₹5 House Gift Box', 'Toys & Educational Games', 'Sri Amman Toys', 'toys', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/toys/₹5 Jumping Boll (36pcs).jpg', '₹5 Jumping Boll (36pcs)', 'toys');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1123', '₹5 Jumping Boll (36pcs)', 'Toys & Educational Games', 'Sri Amman Toys', 'toys', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/toys/₹5 Paper Soap 🫧.jpg', '₹5 Paper Soap 🫧', 'toys');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1124', '₹5 Paper Soap 🫧', 'Toys & Educational Games', 'Sri Amman Toys', 'toys', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/toys/₹5 Puzzle Box actors naruto cartoon mixing.jpg', '₹5 Puzzle Box actors naruto cartoon mixing', 'toys');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1125', '₹5 Puzzle Box actors naruto cartoon mixing', 'Toys & Educational Games', 'Sri Amman Toys', 'toys', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/toys/₹5 Round Wheel.jpg', '₹5 Round Wheel', 'toys');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1126', '₹5 Round Wheel', 'Toys & Educational Games', 'Sri Amman Toys', 'toys', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/toys/₹5 Spinner.jpg', '₹5 Spinner', 'toys');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1127', '₹5 Spinner', 'Toys & Educational Games', 'Sri Amman Toys', 'toys', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/toys/₹5 Water Ball.jpg', '₹5 Water Ball', 'toys');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1128', '₹5 Water Ball', 'Toys & Educational Games', 'Sri Amman Toys', 'toys', 5, 'Sri Amman Toys Catalogue', 'Active');
INSERT INTO gallery (image_url, caption, category) VALUES ('images/toys/₹5 White Nakham.jpeg', '₹5 White Nakham', 'toys');
INSERT INTO products (product_id, description, product_type, brand, model_number, rate, source, status) VALUES ('SAT-1129', '₹5 White Nakham', 'Toys & Educational Games', 'Sri Amman Toys', 'toys', 5, 'Sri Amman Toys Catalogue', 'Active');